# timestamp column info
timestamp_col: datetime
timestamp_tz: UTC # see list of possible time zones at https://gist.github.com/heyalexej/8bf688fd67d7199be4a1682b3eec7568
timestamp_format: '%Y-%m-%d %H:%M:%S+00:00'
local_tz: 'America/Detroit'

# metadata column info
site_col: site_name
lat_col: lat
lon_col: lon
type_col: site_type
city: detroit

# is data in wide format? (one column per pollutant)
wide_format: false 

# if data is in long format, specify the pollutant_col and value_col.
pollutant_col: parameter # Column name with pollutant labels
value_col: value # Column name with measurements

# add your pollutant names and units
# for wide data, match pollutant names to the columns with measurements for that pollutant
# for long data, pollutant names appear in pollutant_col
pollutants: 
    "PM2.5":
        name: "pm25" # fill these with info from your data
        units: "ug/m3"
    "PM10":  
        name: "pm10" 
        units: "ug/m3"
    "O3":
        name: "o3" 
        units: "ug/m3"
    "NO2": 
        name: "no2" 
        units: "ug/m3"
    "SO2": 
        name: "so2" 
        units: "ug/m3"
    "CO": 
        name: "co" 
        units: "ppm"

# data download info
data_source: openaq
bounding_box: [-83.2878, 42.2550, -82.9103, 42.4504]